
name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wrangler
        run: npm i -g wrangler

      - name: Configure Cloudflare env
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          # يقرأها wrangler من هذه المتغيرات
          echo "CLOUDFLARE_ACCOUNT_ID=$CF_ACCOUNT_ID" >> $GITHUB_ENV
          echo "CLOUDFLARE_API_TOKEN=$CF_API_TOKEN" >> $GITHUB_ENV

      - name: Set Worker secrets
        env:
          KONNECT_API_KEY: ${{ secrets.KONNECT_API_KEY }}
          KONNECT_WALLET_ID: ${{ secrets.KONNECT_WALLET_ID }}
        run: |
          # نضيف الأسرار للـWorker (لن تظهر في السجلات)
          echo -n "$KONNECT_API_KEY"   | wrangler secret put KONNECT_API_KEY --yes
          echo -n "$KONNECT_WALLET_ID" | wrangler secret put KONNECT_WALLET_ID --yes

      - name: Deploy
        env:
          # اختياري: لو حاب تغيّر قاعدة API للإنتاج بدون تعديل wrangler.toml
          KONNECT_BASE_OVERRIDE: ${{ secrets.KONNECT_BASE_OVERRIDE }}
        run: |
          # افتراضيًا sandbox لو ما أرسلت override
          if [ -z "$KONNECT_BASE_OVERRIDE" ]; then
            wrangler deploy
          else
            wrangler deploy --var KONNECT_BASE:"$KONNECT_BASE_OVERRIDE"
          fi
